fname = input("Enter First Name: ")
lname = input("Enter Last Name: ")
mname = input("Enter Middle Name: ")
bday = input("Enter Birthday: ")
gender = input("Enter Gender: ")
add = input("Enter Address: ")
course = input("Enter Course: ")
level = input("Enter Year Level: ")

print("Personal Information")
print("First Name:", fname)
print("Last Name:", lname)
print("Middle Name:", mname)
print("Birthday:", bday)
print("Gender:", gender)
print("Address:", add)
print("Course:", course)
print("Year Level:", level)
